### ISSUE TITLE
Support `activate` event on macOS

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tao#218] opened 2021-10-11 13:50 UTC
**Is your feature request related to a problem? Please describe.**
On macOS clicking the applications dock icon does a few things depending on the context:
- launch the application
- focus windows
- if all windows are closed create a new one
Afaik all these events are communicated through the `appkit::NSEventSubtype::NSApplicationActivatedEventType` event. Can we expose this even to consumers somehow? 

**Describe the solution you'd like**
Add an `ActivationEvent` member to the `tao::event::Event` enum. This would mirror the `appkit::NSEventSubtype::NSApplicationActivatedEventType` event.

**Describe alternatives you've considered**
Some of this can be implemented through the use of `WindowEvent::Focus`, but that will only be fired on a per-window basis, not when all windows are closed.

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

**Comment by xuchaoqian** [comment] 2021-12-16 16:47
Sound great! 
May I ask what's the status of this feature?

**Comment by 0rvar** [comment] 2023-01-12 12:07
I am very interested in this feature as well

**Comment by BB-fat** [comment] 2024-04-28 06:39
Three years have passed and this feature has not been implemented yet?

**Comment by martpie** [comment] 2024-04-28 09:25
See here for a working example, the feature exists, it's just not very explicit

https://github.com/martpie/museeks/blob/tauri/src-tauri/src/plugins/app_close.rs

Or there reply to the main Tauri issue: https://github.com/tauri-apps/tauri/issues/3084#issuecomment-1477675840

**Comment by BillGoldenWater** [comment] 2024-04-28 09:32
> See here for a working example, the feature exists, it's just not very explicit
> 
> https://github.com/martpie/museeks/blob/tauri/src-tauri/src/plugins/app_close.rs

it's actually not the same thing,

the activate event is a event that you can handle when user click the dock icon,

the plugin just mimic the effect of show the window on the event, and if you use the plugin, the window will not actually close when user click the close button

**Comment by BB-fat** [comment] 2024-04-28 09:38
> See here for a working example, the feature exists, it's just not very explicit
> 
> https://github.com/martpie/museeks/blob/tauri/src-tauri/src/plugins/app_close.rs
> 
> Or there reply to the main Tauri issue: [tauri-apps/tauri#3084 (comment)](https://github.com/tauri-apps/tauri/issues/3084#issuecomment-1477675840)

This solution is useless when the business has multiple windows.

**Comment by thewh1teagle** [comment] 2024-04-28 20:57
I'm also interested in `active` event on macOS. I use [single-instance](https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/single-instance) plugin in v2 project, and I keep the app running even when the main window is closed, but when the user try to launch another instance, macOS focus the current running instance by default but it doesn't trigger events on the app so it focus nothing.

**Comment by pronebird** [comment] 2024-04-30 16:04
I can't believe it takes that long to send an event in response to `applicationDidBecomeActive`. What can be done to push this forward?

**Comment by BillGoldenWater** [comment] 2024-04-30 16:15
since tao is a fork of [winit](https://github.com/rust-windowing/winit) and it's planned to keep features sync with it(#470) for [switch back](https://github.com/tauri-apps/tao?tab=readme-ov-file#acknowledgement) to it in the feature, so probably need this issue(rust-windowing/winit#2120) be completed

**Comment by amrbashir** [comment] 2024-04-30 16:20
the switch back to winit has been delayed indefinitely for now, let's move forward and worry about the switch later.

**Comment by FabianLars** [comment] 2024-04-30 16:20
We've broken compatibility with 2120 a few times already anyway ^^

**Comment by pronebird** [comment] 2024-05-01 15:05
As @BillGoldenWater mentioned and I had verified that NSApplicationActivatedEventType is not a solution. For example when user closes the last visible window, the app stays focused, i.e the menu is still visible in the top left corner in the menubar and the click on dock does not fire `NSApplicationActivatedEventType`. Instead `applicationShouldHandleReopen` is called on `AppDelegate`.

**Comment by thewh1teagle** [comment] 2024-05-01 15:15
@pronebird It's not intended to do that. It's a "focus" event in the app (not on windows). It's useful if you click the icon when the app isn't in focus, or when the app is closed to the tray and you try to open it from applications or from the dock. It will focus the app, and the activated event will emit. Could you clarify why you need the event when the user clicks the icon while the app is already in focus?

**Comment by BillGoldenWater** [comment] 2024-05-01 15:20
This issue by my understand is about emit an event when click on the dock icon regardless the state of focus

**Comment by BillGoldenWater** [comment] 2024-05-01 15:23
and a side note, the [appkit::NSEventSubtype::NSApplicationActivatedEventType](https://developer.apple.com/documentation/appkit/nsapplicationactivatedeventtype) is deprecated

**Comment by pronebird** [comment] 2024-05-01 15:52
> @pronebird It's not intended to do that. It's a "focus" event in the app (not on windows). It's useful if you click the icon when the app isn't in focus, or when the app is closed to the tray and you try to open it from applications or from the dock. It will focus the app, and the activated event will emit. Could you clarify why you need the event when the user clicks the icon while the app is already in focus?

The problem is that when the user closes the last visible window, the app stays in focus. To my understanding, the click on dock tile would typically open a new "untitled document" window, in a typical document based native app. But there is no hook for that in tauri.

As a side note, I [already capture](https://gist.github.com/pronebird/46fdc921bc7970867283000b30420074) `NSApplicationDidBecomeActiveNotification` via `CFNotificationCenter` and that works but doesn't cut it because it's only triggered when the app regains focus but not when all windows are closed and the user clicks on dock tile while the app is still focused.

I would actually like to show the new window if user clicks on dock tile when there are no visible windows left. This is what [`applicationShouldHandleReopen:hasVisibleWindows:`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen) is for.

**Comment by thewh1teagle** [comment] 2024-05-01 16:08
Thanks, so I tested [shouldHandleReopen](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen) from https://github.com/tauri-apps/tao/pull/517 and it works great on `macOS 14.4.1 aarch64` 
It worked when:
- User click the app icon in the `dock` (always emit)
- User click the app icon in `Applications folder` / `launcher` when app already running (Useful for [single instance plugin](https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/single-instance))

I hope that it will be merged soon, added to Wry, and make its way into Tauri finally

Update: merged to tao and soon [to tauri](https://github.com/tauri-apps/tauri/pull/4865)

**Comment by pronebird** [comment] 2024-05-01 16:13
> Thanks, so I tested [shouldHandleReopen](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen) from #517 and it works great on `macOS 14.4.1 aarch64` It worked when:
> 
> * User click the app icon in the `dock` (always emit)
> * User click the app icon in `Applications folder` / `launcher` when app already running (Useful for [single instance plugin](https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/single-instance))
> 
> I hope that it will be merged soon, added to Wry, and make its way into Tauri finally

yeah totally that should also work for single instance plugin and eliminate the need for flock-based mutex or whatever is used there.

**Comment by FabianLars** [comment] 2024-05-01 17:57
It won't work for the single instance plugin, or at least can't replace the current logic. The single instance plugin on MacOS really only handles when the app is opened from the console which doesn't emit this event (otherwise the MacOS native single instance mechanism would trigger already)

**Comment by pronebird** [comment] 2024-05-01 19:14
> It won't work for the single instance plugin, or at least can't replace the current logic. The single instance plugin on MacOS really only handles when the app is opened from the console which doesn't emit this event (otherwise the MacOS native single instance mechanism would trigger already)

Any console or just `npm run tauri dev`? If dev mode is a concern then perhaps it doesn't matter all that much as it should work fine in production.

**Comment by FabianLars** [comment] 2024-05-01 19:41
any console. the contributor(s) iirc had a cli interface for their app in build mode too and that didn't trigger the macos single instance mechanism.

**Closed as completed** 2024-05-02 13:05 UTC
Labels: platform: macOS, type: feature request, priority: medium

**Comment by ayangweb** [comment] 2024-08-24 11:31
> > See here for a working example, the feature exists, it's just not very explicit
> > https://github.com/martpie/museeks/blob/tauri/src-tauri/src/plugins/app_close.rs
> > Or there reply to the main Tauri issue: [tauri-apps/tauri#3084 (comment)](https://github.com/tauri-apps/tauri/issues/3084#issuecomment-1477675840)
> 
> This solution is useless when the business has multiple windows.

Hey 👋, excuse me! Did you implement the `applicationShouldHandleReopen` method for multi-window triggering?
