### ISSUE TITLE
Keyboard shortcuts never trigger on Linux under X11

### ISSUE THREAD

**Issue by rscarson** [tauri-apps/tao#501] opened 2022-07-27 15:55 UTC
Tested in Ubuntu 22.04 under X11 and Wayland.

Shortcut gets bound successfully, but handler never triggers. According to tauri-apps/global-hotkey#28, X11 support should be available in the current version (0.9.1 is what my application is pulling, through Tauri 1.0.0-rc.13).

Bug seems identical to tauri-apps/tao#307, which while still open, was labelled fixed by tauri-apps/tao#313 and tauri-apps/tao#333.

So what is the status of the issue described in tauri-apps/tao#307?

Code below works on Windows platforms, but not in Ubuntu 22.04, neither X11 or Wayland
```rust
fn handle_shortcut() {
    // Never triggered
    println!("in");
}

pub fn bind_shortcut(app_handle: tauri::AppHandle, shortcut: &str, handler: fn(AppHandle)) -> Option<String> {
	let mut gsm = app_handle.global_shortcut_manager();
	gsm.unregister_all().ok()?;
	match gsm.register(shortcut, || { handle_shortcut(); }) {
		Ok(_) => {
                    println!("Registered shortcut: {}", shortcut);
                    None
                },
		Err(e) => {
			// Error
                        println!("Could not register shortcut: {}", e);
			Some("invalid shortcut".to_string())
		}
	}
}
```

**Comment by FabianLars** [comment] 2022-07-27 17:50
Copy pasting my discord message:
> It's open because it's not fixed. And about the relation to tauri-apps/global-hotkey#28, tauri-apps/global-hotkey#28 was opened march 1, and tauri-apps/tao#307 was reopened march 10. tauri-apps/global-hotkey#28 is about the wayland limitation and tauri-apps/tao#307 is open because x11 doesn't work due to a bug. Unfortunately tauri-apps/tao#307 does work for many, _including the main maintainers of tao_, which makes it harder to fix.

Therefore closing this as a duplicate of tauri-apps/tao#307. And a headsup: this may only be fixed in the context of the winit migration :/

**Closed as completed by FabianLars** 2022-07-27 17:50 UTC
