### ISSUE TITLE
window vibrancy feature

### ISSUE THREAD

**Issue by samirdjelal** [tauri-apps/tao#137] opened 2021-07-19 14:41 UTC
it will be great to see window vibrancy feature in Tauri
Here is some examples that made in electron 

https://github.com/arkenthera/electron-vibrancy 
https://github.com/Seo-Rii/electron-acrylic-window/blob/master/src/native/win10.cpp

![image](https://user-images.githubusercontent.com/25848885/126177877-0e0e5c28-2184-45d6-8fb1-5c4e013a0286.png)
![image](https://user-images.githubusercontent.com/25848885/126178294-07697a2d-7cc3-4eb2-83e8-4f0629ef2f13.png)

**Comment by lemarier** [comment] 2021-07-19 14:52
For macOS it should be quite easy;
https://developer.apple.com/documentation/appkit/nsvisualeffectview?language=objc

**Comment by amrbashir** [comment] 2021-07-19 15:13
On Linux, transparency/blur is usually used by the user compositor and we can't control that, however I think I've seen some apps before that use clever tricks to workaround this (I need to do more research). There is also some news about [gtk4 has some blur effect ](https://stackoverflow.com/questions/45456175/gtkis-it-possible-to-achieve-glass-blur-effect-in-gtk)but since I haven't tried it at all, it might not be the expected behavior.
IMO I don't think we should support Linux for this, too much work and users can easily configure their compositer.   

On Windows: 
  - `win7` supports `blur` only (`DWMEnableBlurBehind`).
  - `win8` doesn't support any `blur` method, not to my knowledge at least.
  - `win10` supports `blur` on all versions I think without any problems. It also supports `acrylic` but only on `win10 v1809+` and it will have lags when resizing/moving the window (`SetWindowCompositionAttribute`).
- `win11` is the same as `win10` but also supports `mica` (`DwmSetWindowAttribute`).

**Comment by wusyong** [comment] 2021-07-21 02:34
I'm going to upgrade to gtk4 and see how it goes? 
If that works well, maybe we could add this later.

**Comment by tropicaaal** [comment] 2021-10-24 18:04
Note that Windows 11 also has undocumented APIs for enabling the new Mica blur effects as well.

**Comment by amrbashir** [comment] 2021-10-24 20:54
@Tropix126 is it `SetWindowCompositionAttribute` or something else ?

Edit: According to this [comment](https://github.com/electron/electron/issues/29937#issuecomment-948896250), seems like there is a new variant in `dwmapi.h` that can be used with `DwmSetWindowAttribute` but it is still in preview sdk and not stable.

**Comment by amrbashir** [comment] 2021-12-06 13:53
for anyone interested in this issue, I made a https://github.com/tauri-apps/window-vibrancy to experiment with the feature. it supports tao and tauri and I'd appreciate feedback on different Windows versions, macOS support will be added later. 

Edit: macOS is now supported.

**Comment by tropicaaal** [comment] 2021-12-17 00:41
The lastest insider build of Windows 11 (22523) just got public facing Win32 APIs for Mica and Acrylic composition effects respectively under `DWMWA_SYSTEMBACKDROP_TYPE`:
https://twitter.com/StartIsBack/status/1471262840313065474/

**Comment by amrbashir** [comment] 2023-01-09 22:41
Closing this as https://github.com/tauri-apps/window-vibrancy is enough and will try to include it in tauri@v2 by default.

**Closed as completed by amrbashir** 2023-01-09 22:41 UTC
Labels: platform: Windows, platform: Linux, platform: macOS, type: feature request

**Comment by developomp** [comment] 2023-01-10 02:48
> Closing this as https://github.com/tauri-apps/window-vibrancy is enough and will try to include it in tauri@v2 by default.

Hopefully with Linux support?

**Comment by FabianLars** [comment] 2023-01-10 09:11
> Hopefully with Linux support?

To our knowledge the note in the readme is still accurate, at least if we don't want to force users to install gnome extensions. We'd love to be proven wrong about that though, so if you know something we don't, please reach out to us!
